import "@/app/globals.css";
import { ToastProvider } from "@heroui/react";
import { HeroUIProvider } from "@heroui/react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ToastProvider
          placement="bottom-center"
          toastProps={{
            radius: "lg",
            color: "primary",
            variant: "bordered",
            timeout: 1500,
            hideIcon: true,
          }}
        />
        <HeroUIProvider>
          {children}
        </HeroUIProvider>
      </body>
    </html>
  );
}
